### ISSUE TITLE
imap@8.1 - symbol not found in flat namespace '__emalloc_192'

### ISSUE THREAD

**Issue by ciaran-moore** [shivammathur/homebrew-extensions#2915]
**Describe the bug**
Installed on Mac OSX Ventura 13.1 (22C65) 1.4 GHz Quad-Core Intel Core i5 
Getting the below error when running php via cli

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'imap.so' (tried: /usr/local/lib/php/pecl/20210902-debug/imap.so (dlopen(/usr/local/lib/php/pecl/20210902-debug/imap.so, 0x0009): symbol not found in flat namespace '__emalloc_192'), /usr/local/lib/php/pecl/20210902-debug/imap.so.so (dlopen(/usr/local/lib/php/pecl/20210902-debug/imap.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902-debug/imap.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/php/pecl/20210902-debug/imap.so.so' (no such file), '/usr/local/lib/php/pecl/20210902-debug/imap.so.so' (no such file))) in Unknown on line 0
```
`imap.so` exists in `/usr/local/lib/php/pecl/20210902-debug/imap.so`

**PHP versions**
```
PHP 8.1.14 (cli) (built: Jan 16 2023 18:31:20) (NTS DEBUG)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies
```

**To Reproduce**
Installed via `brew install shivammathur/extensions/imap@8.1`

Tested with `php -m` in terminal.

**Expected behavior**
imap extension to appear in `php -m` and imap extension to be available

**Additional Comment**
I have attempted to debug with gdb to see what is missing but it doesn't want to play ball. Even after following all steps for my version of Mac OSX, I'm still getting `(please check gdb is codesigned - see taskgated(8))` message in gdb, so unable to provide anything more helpful than the above.

**Comment by shivammathur** [comment]
Please reinstall. It should work now

```zsh
brew update
brew reinstall shivammathur/extensions/imap@8.1
```

**Comment by ciaran-moore** [comment]
Sorry for the belated response. I still get the same error after update and reinstall.
I am using the `php@8.1-debug` version of php. 

Is there a separate extension repo for debug versions of php?
